version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-75-245-94.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d6vemeu2sg47on
            ssl: true
            user: qfrrqwzdqviuym
            password: bfde037e1c9f22d1462828f8e5dd4ed37ebd743265377867dcbda422f867c6dd
            migrations: true
